FROM httpd:2.4
COPY ./conf/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./conf/extra/ /usr/local/apache2/conf/extra/
COPY ./conf/options-ssl-apache.conf /etc/letsencrypt/options-ssl-apache.conf

